name: Laravel CI
on: push
jobs:
  laravel-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Php Version
        run: php -v
      
      - name: Composer Version
        run: composer --version